# Neural Networks from Scratch - P.3 The Dot Product

**In calculating the activation functions in future, OL will have a different bias.** 
`but this doesnt concern us now`

If we were making a node from the OL: assume we are receiving 4 parameters from the previous node.

# 4 inputs into 3 neurons

In [36]:
inputs = [1, 2, 3, 2.5] # 4 params from previous node
n_nodes = 3 # no of nodes

weights = [[0.2, 0.8, -0.5, 1.0], # for first neuron
           [0.5, -0.91, 0.26, -0.5], # second
           [-0.26, -0.27, 0.17, 0.87]] # third

bias = [2, 3, 0.5] # since there are 3 nodes
                   # 3 bias for each node

In [37]:
%time output = [sum([inputs[i]*weights[n][i] for i in range(4)])\
             + bias[n] for n in range(n_nodes)]
print(output)

CPU times: user 25 µs, sys: 5 µs, total: 30 µs
Wall time: 36 µs
[4.8, 1.21, 2.385]


# Same operation in numpy

In [38]:
import numpy as np

In [39]:
inputs=np.array(inputs)
weights=np.array(weights)
bias=np.array(bias)

In [40]:
weights

array([[ 0.2 ,  0.8 , -0.5 ,  1.  ],
       [ 0.5 , -0.91,  0.26, -0.5 ],
       [-0.26, -0.27,  0.17,  0.87]])

In [41]:
inputs

array([1. , 2. , 3. , 2.5])

In [42]:
bias

array([2. , 3. , 0.5])

## Broadcasting in numpy to the rescue
Numpy realises `inputs` is only 1D and broadcasts itself 3 more times.

Intuition: Bias shifts the intercept, line equation.

In [43]:
%time output = np.dot(weights,inputs) + bias
# row by row dot product
print(output)

CPU times: user 71 µs, sys: 16 µs, total: 87 µs
Wall time: 71.8 µs
[4.8   1.21  2.385]


#### list comprehension is faster than numpy!
30-40 microseconds with list comprehension
60-90 microseconds with numpy